routes/web.php
<?php

use Illuminate\Support\Facades\Route;


Route::get('/', 'WebController@index')->name('home');
Route::match(['get', 'post'], '/contacto', 'WebController@contacto')->name('contacto');
Route::match(['get', 'post'], '/nosotros', 'WebController@nosotros')->name('nosotros');
Route::match(['get', 'post'], '/servicios', 'WebController@servicios')->name('servicios');
Route::match(['get', 'post'], '/blog', 'WebController@blog')->name('blog');
Route::match(['get', 'post'], '/blog/{id}', 'WebController@blogDetalle')->name('blogDetalle');
Route::match(['get', 'post'], '/us_analisis', 'WebController@us_analisis')->name('us_analisis');


Route::match(['GET', 'POST'], '/admin', 'Admin\AccesoController@login')->name('login');

$admin = ['prefix' => 'panel', 'namespace' => 'Admin', 'middleware' => 'auth'];
Route::group($admin, function() {

    $ctrl = 'AccesoController';
	$as = 'admin';
    Route::get('/dashboard', "$ctrl@dashboard")->name($as.'_dashboard');
    Route::get('/salir', "$ctrl@salir")->name($as.'_salir');

    Route::resource('blog', 'BlogController');
});

app/Models/Blog.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Blog extends Model
{
    use HasFactory;
    protected $table='blog';
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Admin/AccesoController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Validator;
use App\Http\Controllers\Controller;

class AccesoController extends Controller
{
    public function login(Request $request)
	{
		if($request->isMethod('post'))
		{
			$validator = Validator::make($request->all(), [
				'email' => 'required',
				'password' => 'required',
			]);

			if($validator->fails())
			{
				$alert = array(
					'estatus' => 'error',
					'mensaje' => 'Los campos son obligatorios'
				);
				return redirect()->route('login')
				->with('alert', $alert)
				->withInput();
			}
			$email = $request->input('email');
			$password = $request->input('password');

            $credentials = array('email' => $email, 'password' => $password);
			if (Auth::attempt($credentials))
			{
				return redirect()->route('admin_dashboard');
			}

			$alert = array(
				'estatus' => 'error',
				'mensaje' => 'No existe un usuario con esos datos'
			);
			return redirect()->route('login')
			->with('alert', $alert)
			->withInput();
		}else{
			return view('admin.login');
		}
	}
	public function dashboard()
	{
		return view('admin.dashboard');
	}
	public function salir()
	{
		Auth::logout();
		return redirect()->route('login');
	}
}

app/Http/Controllers/Admin/BlogController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;

use App\Models\Blog;
use Image;
use App\Utils\Utils;

class BlogController extends Controller
{
	public function index()
	{
		return view('admin.blog.index')->with('blog',Blog::all());
	}

	public function create()
	{
		return view('admin.blog.create');
	}

	public function store(Request $request)
	{
		DB::beginTransaction();
		try{
			$utils = new Utils;
			$slug = $utils->doSlug($request->input('titulo'));
			$check = Blog::where('slug',$slug)->first();
			if($check == null){
				$blog = new Blog;
				$blog->titulo = $request->input('titulo');
				$blog->keywords = $request->input('keywords');
				$blog->description = $request->input('description');
				$blog->intro = $request->input('intro');
				$blog->imagen = $request->hasFile('imagen') ? self::save_img($blog->imagen, $request->file('imagen'),840,600):$blog->imagen;
				$blog->post = $request->input('post');
				$blog->activo = $request->input('activo');
				$blog->slug = $slug;
				$blog->save();
			}else{
				DB::rollBack();
				$mensaje = 'Ya existe un evento con ese título';

				$alert = array(
					'estatus' => 'warning',
					'mensaje' => $mensaje
				);
				return back()->with('alert', $alert)->withInput();
			}

			DB::commit();
			return redirect()->route('blog.index');
		}catch(\Exception $e){
			DB::rollBack();
			$mensaje = 'Ocurrió un error intenta nuevamente, si el problema persiste contacta al administrador.';
			$data = array(
				'estatus' => 'error',
				'mensaje' => $mensaje
			);
			return back()->with('alert', $data);

		}
	}

	public function show($id)
	{
		//
	}

	public function edit($id)
	{
		return view('admin.blog.edit')->with('blog',Blog::find($id));
	}

	public function update(Request $request, $id)
	{
		DB::beginTransaction();
		try{
			$utils = new Utils;
			$slug = $utils->doSlug($request->input('titulo'));
			$check = Blog::where('slug',$slug)->first();
			// if($check == null){
				$blog = Blog::find($id);
				$blog->titulo = $request->input('titulo');
				$blog->keywords = $request->input('keywords');
				$blog->description = $request->input('description');
				$blog->intro = $request->input('intro');
				// $blog->imagen = $request->input('imagen');
				$blog->imagen = $request->hasFile('imagen') ? self::save_img($blog->imagen, $request->file('imagen'),840,600):$blog->imagen;
				$blog->post = $request->input('post');
				$blog->slug = $slug;
				$blog->save();
			// }else{
			// 	DB::rollBack();
			// 	$mensaje = 'Ya existe un evento con ese título';

			// 	$alert = array(
			// 		'estatus' => 'warning',
			// 		'mensaje' => $mensaje
			// 	);
			// 	return back()->with('alert', $alert)->withInput();
			// }

			DB::commit();
			return redirect()->route('blog.index');
		}catch(\Exception $e){
			DB::rollBack();
			$mensaje = 'Ocurrió un error intenta nuevamente, si el problema persiste contacta al administrador.';
			$data = array(
				'estatus' => 'error',
				'mensaje' => $mensaje
			);
			return back()->with('alert', $data);

		}
	}

	public function destroy($id)
	{
		$blog = Blog::find($id);
		$blog->delete();

		$data = array(
			'estatus' => 'success',
			'mensaje' => "Eliminado correctamente",
			'id' => $id
		);

		return response()->json($data);
	}

	static function save_img($current, $image,$w,$h){
		$pathFile = public_path().'/images/blog';
		if($current != '' && file_exists($pathFile.'/'.$current))
		{
			unlink($pathFile.'/'.$current);
		}

		$image_name = md5(time().rand(0,10)).$w.$h.".".$image->getClientOriginalExtension();
		$img = Image::make($image)
		->resize($w,$h)
		->save('images/blog/'.$image_name);

		return $image_name;
	}
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/WebController.php
<?php

namespace App\Http\Controllers;

use App\Models\Blog;

use Illuminate\Http\Request;

class WebController extends Controller
{
    public function index()
    {
        return view('web.home');
    }

    public function contacto()
    {
        return view('web.contacto');
    }
    public function nosotros()
    {
        return view('web.nosotros');
    }
    public function servicios()
    {
        return view('web.servicios');
    }
    public function blog()
    {
        $blog = Blog::all();
        // return $blog;
        return view('web.blog')->with('blog',$blog);
    }
    public function blogDetalle($id)
    {
        $blogDetalle = Blog::where('slug',$id)->first();
        $ultimos = Blog::where('slug','!=',$id)->limit(3)->get();
        return view('web.blogDetalle')->with('blogDetalle',$blogDetalle)->with('ultimos',$ultimos);
    }
}

resources/views/admin/blog/create.blade.php
@extends('admin.layout')
@section('head')
	<link rel="stylesheet" href="{{ asset('/plugins/keywords/tagsinput.css') }}">
@endsection

@section('contenido')

	<div class="Panel-titulo">
		<h1>Agregar blog</h1>
	</div>
	<div class="Panel">
		<div class="Panel-container-view-actions flex">
			<a class="btn btn--add" href="{{ route('blog.index') }}"">
				Regresar
			</a>
		</div>
		<form action="{{route('blog.store')}}" method="POST" id="form" files="true" enctype="multipart/form-data">
			<input type="hidden" name="_token" value="{{csrf_token()}}">
			<div class="input text">
				<label for="titulo">Titulo</label>
				<input type="text" name="titulo" >
			</div>
			<div class="inputs text">
				<div class="input image">
					<p>*Blog imagen(840x600)</p>
					<div class="container">
						<i class="icon icon-close">x</i>
						<span class="btn btn--save">Seleccionar archivo (jpg, png)</span>
						<input type="file" data-img="imagen_1" name="imagen" id="data-imagen" class="input-file validate[required]"  accept="image/x-png,image/jpeg">
						<div class="imagen">
							<img id="img_imagen_1"  src="#"/>
						</div>
					</div>
				</div>
				<div class="input text">
                    {{-- <label for="imagen">Imagen</label>
                    <input type="text" name="imagen"> --}}
					<label for="keywords">Keywords</label>
					<input type="text" id="keywords" name="keywords">
				</div>
			</div>
			<div class="inputs text">
				<div class="input text">
					<label for="intro">Intro</label>
					<textarea name="intro" id="intro" cols="30" rows="10"></textarea>
				</div>
				<div class="input text">
					<label for="description">Descripcion</label>
					<textarea name="description" id="description" cols="30" rows="10"></textarea>
				</div>
			</div>
            <div class="inputs text">
                <div class="input text">
                    <label for="post">Post</label>
                    <input type="text" name="post">
                </div>
                <div class="input text">
                    <label for="activo">Activo</label>
                    <input type="text" name="activo">
                </div>
            </div>



			<div class="button">
				<button class="btn btn--save btn--large">Guardar</button>
			</div>
		</form>
	</div>
@stop

@section('js')
	<script src="{{ asset('/plugins/keywords/tagsinput.js') }}"></script>
	<script type="text/javascript">
		$(function(){
			$('#menu-blog').addClass('is-selected');

			$('#description').trumbowyg({
				removeformatPasted: true
			});
			$('#intro').trumbowyg({
				removeformatPasted: true
			});
			// $('#keywords').tagsInput({
			// 	placeholder:'Agregar keyword'
			// });
		});
	</script>
@stop

resources/views/admin/blog/edit.blade.php
@extends('admin.layout')
@section('head')
	<link rel="stylesheet" href="{{ asset('/plugins/keywords/tagsinput.css') }}">
@endsection

@section('contenido')

	<div class="Panel-titulo">
		<h1>Editar blog</h1>
	</div>
	<div class="Panel">
		<div class="Panel-container-view-actions flex">
			<a class="btn btn--add" href="{{ route('blog.index') }}">
				Regresar
			</a>
		</div>
		<form action="{{route('blog.update',$blog->id)}}" method="POST" id="form" files="true" enctype="multipart/form-data">
			<input type="hidden" name="_token" value="{{csrf_token()}}">
			@method('PUT')
			<div class="input text">
				<label for="titulo">Titulo</label>
				<input type="text" name="titulo" value="{{$blog->titulo}}">
			</div>
			<div class="inputs text">
				<div class="input image">
                    <p>* Blog imagen (840x600)</p>
                    <div class="container">
                        <i class="icon icon-close">x</i>
                        <span class="btn btn--save">Seleccionar archivo (jpg, png)</span>
                        <input type="file" data-img="imagen_movil" name="imagen" id="data-imagen_movil" class="input-file"  accept="image/x-png,image/jpeg">
                        <div class="imagen">
							<img id="img_imagen_movil" class="is-visible"
							src="{{asset('/images/blog/'.$blog->imagen)}}" alt="CORVUZ"/>
                        </div>
                    </div>
                </div>
				<div class="input text">
					<label for="keywords">Keywords</label>
					<input type="text" id="keywords" name="keywords" value="{{$blog->keywords}}">
				</div>
			</div>
			<div class="inputs text">
				<div class="input text">
					<label for="intro">Intro</label>
					<textarea name="intro" id="intro" cols="30" rows="10">{{$blog->intro}}</textarea>
				</div>
				<div class="input text">
					<label for="description">Descripcion</label>
					<textarea name="description" id="description" cols="30" rows="10">{{$blog->description}}</textarea>
				</div>
			</div>
            <div class="inputs text">
                <div class="input text">
                    <label for="post">Post</label>
                    <input type="text" name="post" value="{{$blog->post}}">
                </div>
                <div class="input text">
                    <label for="activo">Activo</label>
                    <input type="text" name="activo" value="{{$blog->activo}}">
                </div>
            </div>

			<div class="button">
				<button class="btn btn--save btn--large">Guardar</button>
			</div>
		</form>
	</div>
@stop

@section('js')
    <script src="{{ asset('/plugins/keywords/tagsinput.js') }}"></script>
	<script type="text/javascript">
		$(function(){
			$('#menu-blog').addClass('is-selected');

            $('#description').trumbowyg({
                removeformatPasted: true
            });
            $('#intro').trumbowyg({
                removeformatPasted: true
            });
            $('#keywords').tagsInput({
				placeholder:'Agregar keyword'
			});
        });
    </script>
@stop

resources/views/admin/blog/index.blade.php
@extends('admin.layout')


@section('contenido')

	<div class="Panel-titulo">
		<h1>Blogs</h1>
	</div>
	<div class="Panel-container Panel-container-view">
		<div class="Panel-container-view-actions ">
			<a class="btn btn--add" href="{{ route('blog.create') }}">
				Agregar
			</a>
		</div>
		@if($blog->count() > 0)
			<table class="table">
				<thead>
					<tr>
						<th>titulo</th>
						<th>keywords</th>
                        <th>imagen</th>
						<th>Acciones</th>
					</tr>
				</thead>
				<tbody>
					@foreach($blog as $element)
						<tr id="row-{{$element->id}}">
							<td>
								{{ $element->titulo }}
							</td>
							<td>
                                {{ $element->keywords }}
							</td>
                            <td>
                                <img class="imagen" src="{{ asset('/images/blog/'.$element->imagen)}}">
                            </td>
							<td class="Panel-actions">
								<a class="btn btn--primary" href="{{route('blog.edit',array($element->id))}}">
									Editar
								</a>
								<button class="btn btn--delete-no-data" data-url="{{route('blog.destroy',$element->id)}}">Eliminar</button>
							</td>
						</tr>
					@endforeach
				</tbody>
			</table>
		@else
			<p class="not-found">Aún no se han cargado los Blogs al sistema</p>
		@endif
	</div>

@stop

@section('js')
	<script type="text/javascript">
		$('#menu-blog').addClass('is-selected');
	</script>
@stop

resources/views/admin/dashboard.blade.php
@extends('admin.layout')


@section('contenido')

	<div class="Panel">
		<h1>Bienvenido</h1>
		<p>
			Sea usted bienvenido al administrador web de Corvuz. Este Panel de control cuenta con un eficiente sistema de navegación, el cual le facilitará el proceso administrativo que realice. Esperamos que su estadía en nuestro sistema sea grata.
			<br><br>
			A nombre de nuestra empresa, gracias por su preferencia.
		</p>
	</div>

@stop

resources/views/admin/layout.blade.php
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="robots" content="noindex"/>
        <meta id="token" name="csrf-token" content="{{csrf_token()}}">
        <title>Admin</title>
        <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" rel="stylesheet">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <script src="{{asset('/plugins/sweetalert/sweetalert.min.js')}}"></script>
        <link rel="stylesheet" type="text/css" href="{{asset('/plugins/sweetalert/sweetalert.css')}}">
        <link rel="stylesheet" href="{{ asset('/plugins/validationEngine/validationEngine.jquery.css') }}">
        <link rel="stylesheet" href="{{ asset('/plugins/dataTables/jquery.dataTables.min.css') }}">
        <link rel="stylesheet" href="{{ asset('/plugins/trumbowyg/trumbowyg.min.css') }}">
        <link rel="stylesheet" href="{{ asset('/plugins/fancybox/jquery.fancybox.min.css') }}" />
        <link rel="stylesheet" href="{{mix('/css/admin/admin.css')}}">
        @yield('head')
    </head>
    <body>
        <div class="spinner">
            <div id="loading"></div>
        </div>
        <header class="Admin-header">
            <h2>ADMIN CORVUZ</h2>
            <a href="{{ route('admin_salir') }}">
                <span class="material-icons">
                    logout
                </span>
                Cerrar sesión
            </a>
        </header>
    	<div class="Admin-container">
    		<nav class="Admin-menu">
    			<ul>
                    <li id="menu-blog" class="">
                        <a href="{{ route('blog.index') }}">
                            <span class="material-icons">
                                imagen
                            </span>
                            Blogs
                        </a>
                    </li>
    			</ul>
    		</nav>
    		<div class="Admin-panel">
    			@yield('contenido')
    		</div>
    	</div>

        @yield('vue')
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <script src="{{asset('/plugins/validationEngine/jquery.validationEngine.js')}}"></script>
        <script src="{{asset('/plugins/validationEngine/jquery.validationEngine-es.js')}}"></script>
        <script src="{{asset('/plugins/spin.min.js')}}"></script>
        <script src="{{asset('/plugins/dataTables/jquery.dataTables.min.js')}}"></script>
        <script src="{{ asset('/plugins/trumbowyg/trumbowyg.min.js') }}"></script>
        <script src="{{ asset('/plugins/trumbowyg/langs/es.min.js') }}"></script>
        @yield('js')
        <script>
            $(function(){
                @if(Session::get('alert') != null)
                    swal("", "{{Session::get('alert')['mensaje']}}", "{{Session::get('alert')['estatus']}}");
                @endif

                function loadImg(input) {
                    var $img = $(input).data('img');
                    if (input.files && input.files[0]) {
                        var reader = new FileReader();

                        reader.onload = function (e) {
                            $('#img_'+$img).attr('src', e.target.result);
                        };

                        reader.readAsDataURL(input.files[0]);
                        $('#img_'+$img).css('display', 'block');
                    }

                }

                $("div.input input.input-file").change(function(){
                    loadImg(this);
                });

               $('textarea.texteditor').trumbowyg({
                    lang: 'es',
                    btns: [
                        ['undo', 'redo'],
                        ['formatting'],
                        ['strong', 'em', 'del'],
                        ['link'],
                        ['justifyLeft', 'justifyCenter', 'justifyRight', 'justifyFull'],
                        ['unorderedList', 'orderedList'],
                        ['horizontalRule'],
                        ['removeformat'],
                        ['table']
                    ],
                    autogrow: true,
                    removeformatPasted: true
                });

                $('div.Panel-container-view table.table').DataTable({
                    'language' : {
                        "sProcessing":     "Procesando...",
                        "sLengthMenu":     "Mostrar _MENU_ registros",
                        "sZeroRecords":    "No se encontraron resultados",
                        "sEmptyTable":     "Ningún dato disponible en esta tabla",
                        "sInfo":           "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                        "sInfoEmpty":      "Mostrando registros del 0 al 0 de un total de 0 registros",
                        "sInfoFiltered":   "(filtrado de un total de _MAX_ registros)",
                        "sInfoPostFix":    "",
                        "sSearch":         "Buscar:",
                        "sUrl":            "",
                        "sInfoThousands":  ",",
                        "sLoadingRecords": "Cargando...",
                        "oPaginate": {
                            "sFirst":    "Primero",
                            "sLast":     "Último",
                            "sNext":     "Siguiente",
                            "sPrevious": "Anterior"
                        },
                        "oAria": {
                            "sSortAscending":  ": Activar para ordenar la columna de manera ascendente",
                            "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                        }
                    }
                });

                $.ajaxSetup({
                    headers: {'X-CSRF-TOKEN': "{{csrf_token()}}"}
                });

                $('#form').validationEngine({
                    scroll : false
                });

                $('div.Panel-container-view').on('click', 'button.btn--delete', function(){

                    var $this = $(this);
                    var $id = $this.data('id');
                    var $url = $this.data('url');

                    swal({
                        title: "¿Estás seguro?",
                        text: "¿Quiéres eliminar este elemento?",
                        type: "warning",
                        showCancelButton: true,
                        cancelButtonText : 'Cancelar',
                        confirmButtonColor: "#DD6B55",
                        confirmButtonText: "Sí",
                        closeOnConfirm: true
                    }, function(){
                        $('.spinner').show();
                        $.post($url, { id : $id }, function(response){
                            console.log(response);
                            $('.spinner').hide();
                            swal('', response.mensaje, response.estatus);
                            if(response.estatus == 'success')
                            {
                                $('#row-'+$id).slideUp(400, function(){
                                    $(this).delay(400).remove();
                                });
                            }

                        });
                    });
                });

                $('div.Panel-container').on('click', 'button.btn--delete-no-data', function(){

                    var $this = $(this);
                    var $url = $this.data('url');

                    swal({
                    title: "¿Estás seguro?",
                    text: 'Quieres eliminar este elemento',
                    type: "warning",
                    showCancelButton: true,
                    cancelButtonText : 'Cancelar',
                    confirmButtonColor: "#DD6B55",
                    confirmButtonText: "Sí",
                    closeOnConfirm: true
                    }, function(){
                        $('.spinner').show();
                            $.ajax({
                            url : $url,
                            type: 'POST',
                            data: {_method: 'DELETE'},
                            success: function(response) {
                                $('.spinner').hide();
                                swal('', response.mensaje, response.estatus);
                                if(response.estatus == 'success')
                                {
                                    $('#row-'+response.id).slideUp(400, function(){
                                        $(this).delay(400).remove();
                                    });
                                }
                            }
                        });
                    });
                });

                var opts = {
                      lines: 8 // The number of lines to draw
                    , length: 18 // The length of each line
                    , width: 5 // The line thickness
                    , radius: 20 // The radius of the inner circle
                    , scale: 1 // Scales overall size of the spinner
                    , corners: 1 // Corner roundness (0..1)
                    , color: '#c99f53' // #rgb or #rrggbb or array of colors
                    , opacity: 0.25 // Opacity of the lines
                    , rotate: 0 // The rotation offset
                    , direction: 1 // 1: clockwise, -1: counterclockwise
                    , speed: 1 // Rounds per second
                    , trail: 60 // Afterglow percentage
                    , fps: 20 // Frames per second when using setTimeout() as a fallback for CSS
                    , zIndex: 2e9 // The z-index (defaults to 2000000000)
                    , className: 'spinner' // The CSS class to assign to the spinner
                    , top: '50%' // Top position relative to parent
                    , left: '50%' // Left position relative to parent
                    , shadow: true // Whether to render a shadow
                    , hwaccel: false // Whether to use hardware acceleration
                    , position: 'absolute' // Element positioning
                };

                var target = document.getElementById('loading');
                var spinner = new Spinner(opts).spin(target);

            });
        </script>

    </body>
</html>

resources/views/admin/login.blade.php
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Admin</title>
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" rel="stylesheet">
        <link rel="stylesheet" href="{{ asset('/plugins/sweetalert/sweetalert.css') }}">
        <script src="{{ asset('/plugins/sweetalert/sweetalert.min.js') }}"></script>
        <link rel="stylesheet" href="{{ mix('/css/admin/login.css') }}">
        <link rel="shortcut icon" href="{{ asset('/favicon.ico') }}" type="image/x-icon">
        <link rel="icon" href="{{ asset('/favicon.ico') }}" type="image/x-icon">
    </head>
    <body>

        <div class="Login-form">
    		<figure>
        		<img src="{{ asset('/images/corvuz.png') }}" alt="Corvuz">
        	</figure>
            <form action="{{ route('login') }}" class="Login-form-container" method="POST">
                <input type="hidden" name="_token" value="{{csrf_token()}}">
                <div class="input text">
                    <label>Usuario</label>
                    <input type="email" name="email" required="" value="{{ old('email') }}">
                </div>
                <div class="input text">
                    <label>Contraseña</label>
                    <input type="password" name="password" required="" value="{{ old('password') }}">
                </div>
                <div>
                    <button class="btn btn--primary">Entrar</button>
                </div>
	        </form>
        </div>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <script type="text/javascript">
        	$(function(){
                @if(Session::get('alert'))
                    swal('', "{{Session::get('alert')['mensaje']}}", "{{Session::get('alert')['estatus']}}");
                @endif
        		$('.input.text input').on('blur', function(){
        			var $this = $(this);
        			if($this.val())
        			{
        				$this.addClass('used');
        			}
        		});

        		$('.input.text input').each(function(){
        			var $this = $(this);
        			if($this.val())
        			{
        				$this.addClass('used');
        			}
        		});
        	});
        </script>
    </body>
</html>

resources/views/web/blogDetalle.blade.php
@extends('web.layout')
@section('head')
	<title>Blog Detalle -Corvuz</title>
	<link rel="stylesheet" href="{{ mix('/css/blogDetalle.css') }}">
@endsection
@section('contenido')
    <div class="detalle">
        <div class="layout detalle-container">
            <div class="articulo">
                <img src="{{asset('images/blog/'.$blogDetalle->imagen)}}" alt="{{$blogDetalle->titulo}}">
                <h1 id="Titulo">{{$blogDetalle->titulo}}</h1>
                {!!$blogDetalle->description!!}
            </div>
            <div class="detalle-buscador">
				<div class="barra">
					<div class="barra-resultados">
						<h2>Más artículos</h2>
                        @foreach ($ultimos as $item)
						<a href="{{$item->slug}}">{{$item->titulo}}</a>
                        @endforeach
					</div>
				</div>
			</div>
        </div>
    </div>
@endsection